global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@synapse-ai.com'

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'
  - match:
      service: fraud-detection
    receiver: 'fraud-team'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

- name: 'critical-alerts'
  email_configs:
  - to: 'devops@synapse-ai.com'
    subject: 'CRITICAL: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Severity: {{ .Labels.severity }}
      {{ end }}
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    channel: '#alerts-critical'
    title: 'CRITICAL Alert'
    text: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Instance: {{ .Labels.instance }}
      {{ end }}

- name: 'warning-alerts'
  email_configs:
  - to: 'team@synapse-ai.com'
    subject: 'WARNING: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      {{ end }}

- name: 'fraud-team'
  email_configs:
  - to: 'fraud-team@synapse-ai.com'
    subject: 'Fraud Detection Alert: {{ .GroupLabels.alertname }}'
    body: |
      Fraud Detection System Alert
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Instance: {{ .Labels.instance }}
      Severity: {{ .Labels.severity }}
      Time: {{ .StartsAt }}
      
      Dashboard: http://grafana.synapse-ai.com/d/fraud-detection
      Runbook: https://docs.synapse-ai.com/runbooks/{{ .Labels.alertname }}
      {{ end }}
  slack_configs:
  - api_url: 'YOUR_FRAUD_TEAM_SLACK_WEBHOOK'
    channel: '#fraud-detection'
    title: 'Fraud Detection Alert'
    text: |
      {{ range .Alerts }}
      🚨 *{{ .Annotations.summary }}*
      
      *Instance:* {{ .Labels.instance }}
      *Severity:* {{ .Labels.severity }}
      
      <http://grafana.synapse-ai.com/d/fraud-detection|View Dashboard>
      {{ end }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']
